[package]
name = "NFT"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "nft"
path = "./src/nft.rs"
doctest = false
crate-type = ["lib", "cdylib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
